[package]
name = "chip8-emulator"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[profile.release]
debug = 1

[dependencies]
minifb = "0.24.0"
rand = "0.8.5"
native-dialog = "0.6.3"
rust-ini = "0.18.0"
